CREATE TABLE IF NOT EXISTS operations (
  id SERIAL PRIMARY KEY,
  op VARCHAR(20) NOT NULL,
  a DOUBLE PRECISION NOT NULL,
  b DOUBLE PRECISION NOT NULL,
  result DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS op_unique_idx ON operations(op, a, b);